version = 0.1
[default.deploy.parameters]
stack_name = "whisper"
resolve_s3 = true
s3_prefix = "whisper"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DomainName=\"whisper-anonymously\""
image_repositories = []
